version: '2.4'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    working_dir: /apps/
    environment:
      - DJANGO_DB_HOST=mysql
      - ENV=${ENV}
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build: docker/mysql
    container_name: mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=django
      - MYSQL_HOST=localhost
      - MYSQL_USER=counter
      - MYSQL_PASSWORD=counter1123
    healthcheck:
      test: "exit 0"

volumes:
  data-volume:
      driver: local
