# Generated by Django 2.2.4 on 2021-06-21 16:56

from __future__ import unicode_literals
from django.db import models, migrations


def load_account(apps, schema_editor):
    Account = apps.get_model("orders", "AccountModel")
    account_initial = Account(uuid=str('56a7e0d8-d288-11eb-9be0-d7593912b03c'), name='Test Account')
    account_initial.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_accountmodel_ordersmodel'),
    ]

    operations = [
        migrations.RunPython(load_account,),
    ]
